#!/etc/sh
#make a clean-all option
sudo apt-get install python-setuptools

git clone --branch v2 https://github.com/metachris/RPIO.git
sudo python RPIO/setup.py install

sudo apt-get install build-essential libi2c-dev i2c-tools python-dev libffi-dev

git clone https://github.com/bivab/smbus-cffi.git
sudo python smbus-cffi/setup.py install







