#!/etc/sh
#make a clean-all option
sudo apt-get install python-setuptools

echo ">>>installing RPIO"
git clone --branch v2 https://github.com/metachris/RPIO.git
cd RPIO
sudo python setup.py install
cd ../
rm -rf RPIO

echo ">>>installing i2c tools"
sudo apt-get install build-essential libi2c-dev i2c-tools python-dev libffi-dev

sudo apt-get install python-smbus

#raspi-config enable i2c
echo "to enable i2c use the command raspi-config"
echo "then, go to advanced options, select i2c" 






