#!/bin/sh
#run with sudo
#this should install the gstreamer used for video transmission

sudo apt-get install gstreamer1.0-*
sudo apt-get install gstreamer1.0-plugins-bad
sudo apt-get install gstreamer1.0-plugins-ugly
sudo apt-get install gstreamer1.0-plugins-good
sudo apt-get install gstreamer1.0-libav







